### ISSUE TITLE
关于no valid lidar frame

### ISSUE THREAD

**Issue by lplplp603** [chennuo0125-HIT/lidar_imu_calib#11]
我用自己的禾赛64跑出来的数据包进行标定时报错，显示no valid lidar frame 。请问如何处理
![2021-04-19_12 43 18](https://user-images.githubusercontent.com/81816813/115182615-e3fa2d80-a09f-11eb-9fc8-97222876022b.jpg)

**Comment by chennuo0125-HIT** [comment]
应该是imu和雷达时间戳没法对齐，请检查一下你的imu数据和雷达数据的时间戳是否一致
