### ISSUE TITLE
对于数据集有要求么

### ISSUE THREAD

**Issue by HRex39** [chennuo0125-HIT/lidar_imu_calib#17]
感谢作者的工作！
想请问一下这套方法适合无人车么？
对于数据集，车辆需要行驶怎么样的轨迹呢？需要绕八字么？

**Comment by HRex39** [comment]
https://blog.csdn.net/u012700322/article/details/117021836

**Comment by sunhao-seu** [comment]
同问~ 求解答 @mingjitianming @chennuo0125-HIT

**Comment by JACKLiuDay** [comment]
Hi，thanks for your great work!
Are there any special requirements when collecting imu and velodyne data?
Could you share your bag to us?

**Comment by CycloneC** [comment]
@HRex39 你已经解决了吗，对数据集有啥要求？

**Comment by pedestrain123** [comment]
> 感谢作者的工作！ 想请问一下这套方法适合无人车么？ 对于数据集，车辆需要行驶怎么样的轨迹呢？需要绕八字么？

请问您标定精度怎么样？
