### ISSUE TITLE
请问如何进行雷达和惯导的时间同步？

### ISSUE THREAD

**Issue by Soverngity** [chennuo0125-HIT/lidar_imu_calib#2]
目前雷达是禾赛的Pandar40，请问您在标定前如何进行时间的同步？

**Comment by chennuo0125-HIT** [comment]
你可以参照ros的message_filters功能包进行多传感器的时间同步，链接 http://wiki.ros.org/message_filters

**Comment by zhh2005757** [comment]
> 你可以参照ros的message_filters功能包进行多传感器的时间同步，链接 http://wiki.ros.org/message_filters

也就是现在的代码没有写时间同步的程序，需要我们自己写是吗？

**Comment by yinhaosen** [comment]
我试过ros的message_filters写的软同步，好像时间同步对标定结果影响并不大，只要你雷达和imu对应时间不要相差太多应该问题不大

**Comment by pedestrain123** [comment]
> 我试过ros的message_filters写的软同步，好像时间同步对标定结果影响并不大，只要你雷达和imu对应时间不要相差太多应该问题不大

请问您标定精度可以达到多少？
