### ISSUE TITLE
Doesnt support livox lidars?? -  "No valid lidar frame"

### ISSUE THREAD

**Issue by ManChrys** [chennuo0125-HIT/lidar_imu_calib#23]
Probably doesnt support livox (static) lidars??

Because i have a
lidar mid 40 imu xsens mti g 710 gnss ins

![1](https://user-images.githubusercontent.com/67521662/187635896-031370dc-56ed-4170-9591-1ffa376a296d.png)
![2](https://user-images.githubusercontent.com/67521662/187635911-e60cfc6d-5fc1-438c-8d47-ba61cafc2c08.png)

**Comment by ManChrys** [comment]
It works #19

**Comment by pedestrain123** [comment]
> Probably doesnt support livox (static) lidars??
> 
> Because i have a lidar mid 40 imu xsens mti g 710 gnss ins
> 
> ![1](https://user-images.githubusercontent.com/67521662/187635896-031370dc-56ed-4170-9591-1ffa376a296d.png) ![2](https://user-images.githubusercontent.com/67521662/187635911-e60cfc6d-5fc1-438c-8d47-ba61cafc2c08.png)

请问您标定精度怎么样？
